markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: cnupdog
host: cnupdog.github.com

custom:
    category:
        programming: Programming
        devops: Devops
        photos: Photos
        django: Django
        others: Others
    categories:
      - name:  programming
        title: Programming
      - name:  devops
        title: Devops
      - name:  photos
        title: Photos
      - name:  django
        title: Django
      - name:  others
        title: Others
meta:
    author:
        name: cnupdog
        email: cnupdog@gmail.com
        disqus: cnupdog                             # Disqus缩略标识
        gcse: 006199422454250533469:dtpdx7sj9zi     # Google自定义搜索标识ID
        github: cnupdog                             # GitHub账号
        gravatar: 19a5163ef85c55fd85be244d7f719327  # Gravatar头像标识
        selfdesc: Coder | 忧伤的吃货 | 工作两年 | 理想在远方                                                                        # 自我介绍
    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
