markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: cnupdog
host: cnupdog.github.com

custom:
    category:
        default: Default Category
        another: Another Category
    categories:
      - name:  default
        title: Default Category

      - name:  another
        title: Another Category

meta:
    author:
        name: cnupdog
        email: cnupdog@gmail.com
        disqus: your-disqus-short-name              # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: cnupdog                             # GitHub账号
        gravatar: 19a5163ef85c55fd85be244d7f719327  # Gravatar头像标识
        selfdesc: Alipay Code Farmer                # 自我介绍
    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
